import './globals.css'

import Auth from "./auth";


export const metadata = {
  title: "Slack App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <body><Auth>{children}</Auth></body>
    </html>
  );
}
