
import './globals.css'

import Datas from './auth'


export const metadata = {
  title: "Slack App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body>{children}</body> */}
      <body><Datas>{children}</Datas></body>
    </html>
  );
}
